server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        boot:
          allow_jdbc_metadata_access: false
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToClosedEnabled: true
  retry:
    instances:
      userService:
        maxAttempts: 3
        waitDuration: 500ms

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
  health:
    circuitbreakers:
      enabled: true
