apiVersion: v1
kind: Secret
metadata:
  name: order-service-db
  namespace: minicommerce
  labels:
    app: order-service
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: change-me-root-password
    MYSQL_USER: user_service
    MYSQL_DATABASE: order_db
    MYSQL_PASSWORD: change-me-user-password
    SPRING_DATASOURCE_USERNAME: user_service
    SPRING_DATASOURCE_PASSWORD: change-me-user-password
